cita/urls.py
from django.conf.urls import patterns, url
from cita.views import ReservarCitaView, CitasListView, BusquedaCitasView, eliminar_cita_view, CitaEditView, cita_view

urlpatterns =[ 
    # Examples:
    # url(r'^$', 'proyecto_django.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^$',  views.registro_view, name='registro_view'),
    #url(r'^$',  CitaView.as_view(), name='cita_view'),
    #url(r'reservarcita/',  ReservarCitaView.as_view(), name='reservar_cita_view'),
    url(r'^$',  ReservarCitaView.as_view(), name='reservar_cita_view'),
    url(r'^eliminar/',  eliminar_cita_view, name='cita_delete_view'),
    #url(r'citas/edit/(?P<id_cita>[0-9]+)/$', CitaEditView.as_view(), name='cita_edit'),
    url(r'citas/edit/(?P<id_cita>[0-9]*)$', CitaEditView.as_view(), name='cita_edit'),    
    url(r'busqueda_citas/', BusquedaCitasView.as_view(), name='busqueda_citas'),
    url(r'citas/', CitasListView.as_view(), name='citas_list'),    
    url(r'cita/(?P<id_cita>[0-9]*)$', cita_view, name='cita_view')
]

home/urls.py
from django.conf.urls import patterns, url
from home.views import *

urlpatterns = [
    # Examples:
    # url(r'^$', 'proyecto_django.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$',  index_view, name='index_view'),
    url(r'^login/',  login_view, name='login_view'),
    url(r'^logout/$',  logout_view, name='logout_view'),
    url(r'^admin_usuarios/$',  AdminUsuariosView.as_view(), name='admin_usuarios'),
    url(r'^usuarios_permisos/$',  AdminUsuariosPermisosView.as_view(), name='usuarios_permisos'),
    #url(r'^registro/$',  views.registro_view, name='registro_view'),
]

kinderzentrum/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Examples:
    # url(r'^$', 'kinderzentrum.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^registro/', include('registro.urls')),
    url(r'^', include('home.urls')),
    url(r'^cita/', include('cita.urls')),
    url(r'^asistencia/', include('asistencia.urls')),
    url(r'^pagos/', include('pago.urls')),
    url(r'^reset/password_reset/$', 'django.contrib.auth.views.password_reset', name='reset_password_reset1'),
    url(r'^reset/password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),
    url(r'^change/password/$','home.views.change_password', name='changepassword'),

]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from django.forms.extras.widgets import SelectDateWidget
import datetime
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group
from django.forms import formset_factory, modelformset_factory
from django.views.generic.edit import UpdateView
from django import template
#from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(label="",widget=forms.TextInput(attrs={'placeholder': 'Usuario','autofocus':'autofocus'}))
    password = forms.CharField(label="",widget=forms.PasswordInput(render_value=False, attrs={'placeholder': 'Contraseña'}))


class UserCreateForm(UserCreationForm):
	password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput(render_value=False, attrs={'placeholder': 'Contraseña','class':'form-control'}))
	password2 = forms.CharField(label="Repita contraseña", widget=forms.PasswordInput(render_value=False, attrs={'placeholder': 'Contraseña','class':'form-control'}))
	grupos = forms.ModelMultipleChoiceField(queryset=None,widget=forms.CheckboxSelectMultiple())

	def __init__(self, *args, **kw):
	    super(UserCreateForm, self).__init__(*args, **kw)
	    self.fields['grupos'].queryset=Group.objects.all()

	class Meta:
		model = User
		fields = ('username', 'first_name' , 'last_name','email', 'password1', 'password2','grupos')
		widgets = {
				   'email': forms.EmailInput(attrs={'placeholder': 'email@email.com','class':'form-control'})
					}

	def save(self, commit=True):
		user = super(UserCreateForm, self).save(commit=False)
		user.mail = self.cleaned_data['email']

		print self.cleaned_data['grupos']
		if commit:
			user.save()
			user.groups = self.cleaned_data['grupos']
			user.save()
		return user

	def get_mensaje(self):
		return self.cleaned_data['first_name'] + ' ' + self.cleaned_data['last_name']

	def get_permisos(self):
		return self.cleaned_data['grupos']


class UserForm(ModelForm):
	#required=False para que al evaluar la función clean retorne True así tenga campos vacíos (lo cuál es correcto)
	grupos = forms.ModelMultipleChoiceField(queryset=None, widget=forms.CheckboxSelectMultiple(), required=False)

	def __init__(self, *args, **kw):
	    super(UserForm, self).__init__(*args, **kw)
	    self.fields['grupos'].queryset = Group.objects.all()
	    self.fields['grupos'].initial = Group.objects.filter(user=self.instance.id)
	    self.fields['username'].widget.attrs['readonly'] = True

	class Meta:
		model = User
		fields = ('username', 'first_name' ,)

	def save(self, commit=False):
		user = self.instance
		user.groups = self.cleaned_data['grupos']
		return user

	def clean(self):
		cleaned_data = super(UserForm, self).clean()


UsuariosFormset = modelformset_factory(User, form=UserForm, extra=0)

class ChangePasswordForm(forms.Form):
    newpassword = forms.CharField(label="Nueva Contraseña", widget=forms.PasswordInput(attrs={'placeholder': 'Contrasenia'}))
    renewpasssword = forms.CharField(label="Repita nueva contraseña", widget=forms.PasswordInput(attrs={'placeholder': 'Repita nueva contrasenia'}))

    def clean(self):
        cleaned_data = super(ChangePasswordForm, self).clean()
        newpassword = cleaned_data.get('newpassword')
        renewpasssword = cleaned_data.get('renewpasssword')
        if newpassword != renewpasssword:
            raise forms.ValidationError("Las contraseñas deben ser iguales")
            #self.add_error('renewpasssword', 'Las contraseñas deben ser iguales')



'''
class RegistroUsuario(forms.Form):
    nombre = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Nombres','autofocus':'autofocus'}))
    apellido = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Apellidos'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Usuario'}))
    password = forms.CharField(widget=forms.PasswordInput(render_value=False, attrs={'placeholder': 'Contraseña','class':'form-control'}))
    repeat_password = forms.CharField(widget=forms.PasswordInput(render_value=False, attrs={'placeholder': 'Contraseña','class':'form-control'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder': 'email@email.com','class':'form-control'}))
'''

home/views.py
# -*- encoding: utf-8 -*-
from django.shortcuts import render, render_to_response, redirect
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponseRedirect
from django.template import RequestContext
from home.forms import *
from django.views.generic import View
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import User, Group, Permission
from django.contrib.auth.decorators import login_required

# Create your views here.


def index_view(request):
    if request.user.is_authenticated():
        #grupos = request.user.groups.all()
        user = request.user
        '''
        Aqui vamos a colocar las condiciones para que se habiliten las condiciones que el usuario
        va a usar
        '''
        registro = user.has_module_perms('registro')
        #registro = grupos.filter(name='registro').count() == 1
        ctx = {'registro':registro,'pagina_actual':'inicio'}
        return render(request, 'base.html', ctx)
    else:
        return render(request, 'base.html')


def login_view(request):
    mensaje = ""
    print "hghjgfhjgj"
    if request.user.is_authenticated():
    	#si esta autenticado redirecciona al formulario
        print "redirect"
        return HttpResponseRedirect('/')
    else:
        if request.method == "POST":
            print "post"
            form = LoginForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                #print "hghjgfhjgj"
                usuario = authenticate(username=username,password=password)
                if usuario is not None and usuario.is_active:
                    login(request,usuario)
                    return HttpResponseRedirect('/')
                else:
                    mensaje = "Usuario y/o contraseña incorrecto"
        form = LoginForm()
        ctx = {'form':form,'mensaje':mensaje}
        return render_to_response('home/login.html',ctx,context_instance=RequestContext(request))


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

@login_required
def change_password(request):
    #newpassword = request.POST.get("newpassword")
    #renewpasssword = request.POST.get("renewpasssword")
    #
    if request.method == 'GET':
        form = ChangePasswordForm()
    else:
        username = request.user.username
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            newpassword = request.POST.get("newpassword")
            u = User.objects.get(username__exact=username)
            u.set_password(newpassword)
            u.save()
            return redirect('/')
    return render(request,'home/cambio_contrasenia.html', {'form': form})

class AdminUsuariosView(PermissionRequiredMixin, View):
    permission_required = ('auth.add_user')
    template_name = 'home/admin_usuarios.html'

    def get(self, request, *args, **kwargs):
        registro_usuario = UserCreateForm()
        ctx = {'registro_usuario':registro_usuario, 'pagina_actual':'manejo_usuarios'}
        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        registro_usuario = UserCreateForm(request.POST)
        if registro_usuario.is_valid():
            user = registro_usuario.save()
            mensaje = registro_usuario.get_mensaje()
            grupos = registro_usuario.get_permisos()
            ctx = {'registro_usuario_correcto':True, 'mensaje':mensaje, 'permisos':grupos, 'pagina_actual':'manejo_usuarios'}
            return render(request, self.template_name, ctx)
        else:
            return render(request, self.template_name, {'registro_usuario':registro_usuario})


class AdminUsuariosPermisosView(PermissionRequiredMixin, View):
    permission_required = ('auth.add_user')
    template_name = 'home/admin_usuarios.html'

    def get(self, request, *args, **kwargs):
        #únicamente se pueden modificar usuarios que no sean superusuarios
        usuarios = UsuariosFormset(queryset=User.objects.exclude(is_superuser=1))
        ctx = {'usuarios':usuarios, 'pagina_actual':'manejo_usuarios'}
        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        usuarios_formset = UsuariosFormset(request.POST)
        if usuarios_formset.is_valid():
            for user in usuarios_formset:
                user.save()
        ctx = {'usuarios':usuarios_formset, 'pagina_actual':'manejo_usuarios'}
        return render(request, self.template_name, ctx)

templates/home/admin_usuarios.html
{% extends 'base.html' %}
{% block title %} Kinderzentrum - Administración de usuarios {% endblock %}

{% block css %}
    <link rel="stylesheet" href="/static/css/jquery-ui.css" />
    <link rel="stylesheet" href="/static/css/bootstrap.css" />
    <link rel="stylesheet" href="/static/css/admin_usuarios.css" />   
{% endblock css %}
	
{% block js %}

{% endblock js %}

{% block content %}

	{% if registro_usuario %}
		<div id="registro_usuario">
			<form action="." method="POST">
				{% csrf_token %}	
				<div id="panel_registro_usuario" class="show panel panel-default">
					<div class="panel-heading">Nuevo Usuario</div>		
					<div class="panel-body">
						<div id="errorMsg" class="fade-in one">{{ mensaje }}</div>
						{{ registro_usuario.as_p }}
						<input id="loginBtn" class="btn btn-default" type="submit" value="Guardar">
					</div>
				</div>							
			</form>
		</div>

	{% elif registro_usuario_correcto %}
	<div id="registro_usuario_correcto">		
		<ul id="permisos">
			<div id="panel_registro_usuario_correcto" class="show panel panel-default" style="margin: 0px 5%;">
				<div class="panel-heading">Usuario Creado</div>		
				<div class="panel-body">
					Usuario <b>{{ mensaje }}</b> agregado exitosamente!
					{% for per in permisos %}
					<li>{{ per|title }}</li>
					{% endfor %}
				</div>
			</div>		
		</ul>
	</div>

	{% elif usuarios %}
	<div id="usuarios">
		<div id="panel_permisos_usuario" class="show panel panel-default">
			<div class="panel-heading">Permisos de Usuarios</div>		
			<div class="panel-body">
				<form action="." method="POST">
				{% csrf_token %}	
				{{ usuarios.management_form }}
			  	<table class="table table-bordered table-condensed">
	                <tr>
	                    <th>Nombre de usuario</th>
	                    <th>Nombre</th>
	                    <th>Permisos</th>
	                </tr>
	                {% for form in usuarios %}
	                    {{ form.id }}
	                    <tr class="formset-usuario_set">
	                        <td class="adjust3">{{form.username}}</td>
	                        <td class="adjust3">{{form.first_name}}</td>
	                        <td>{{form.grupos}}</td>
	                    </tr>
	                {% endfor %}
	            </table>
	            <input id="loginBtn" class="btn btn-default" type="submit" value="Guardar">
	            </form>
	        </div>	
        </div>
	</div>
	{% endif %}

{% endblock %}

templates/home/cambio_contrasenia.html
{% extends 'base.html' %}
{% block title %} Kinderzentrum - Administración de usuarios {% endblock %}

{% block css %}
    <link rel="stylesheet" href="/static/css/jquery-ui.css" />
    <link rel="stylesheet" href="/static/css/bootstrap.css" />
    <link rel="stylesheet" href="/static/css/admin_usuarios.css" />

{% endblock css %}

{% block js %}

{% endblock js %}

{% block title_name %}: Cambio de contraseña{% endblock %}


{% block content %}
<div class="container">
      <div class="card card-container">
        <form action="{% url 'changepassword' %}" method="POST" class="form-signin" >{% csrf_token %}


              <div id="errorMsg" class="fade-in one">{{ form.non_field_errors}}</div>
              <input type="password" id="id_newpassword" name="newpassword" class="form-control" placeholder="Contraseña" required>
              <input type="password" id="id_renewpasssword" name="renewpasssword" class="form-control" placeholder="Repita contraseña" required>

              <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Cambiar contraseña</button>
          </form><!-- /form -->

      </div><!-- /card-container -->
  </div><!-- /container -->

{% endblock %}

templates/home/login.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="es">
<head>
    <title>{% block title %}Login{% endblock %}</title>

    {% block css %}
    <link rel="stylesheet" href="/static/css/jquery-ui.css" />
    <link rel="stylesheet" href="/static/css/bootstrap.css" />
    <link rel="stylesheet" href="/static/css/login.css" />
    {% endblock css %}

    {% block js %}
	<script src="/static/js/jquery-1.9.1.js"></script>
	<script src="/static/js/jquery-ui.js"></script>
	<script src="/static/js/bootstrap.js"></script>
    {% endblock js %}
</head>

<body>
	{% block content %}
	<center><img src="../static/images/kz_logo2.png" width=100 height=100 style="margin-top: 10px;"></center>
	<h1>Kinderzentrum</h1>
	<h2>Ingrese al sistema</h2>

	<!--<div id="singin">
		<img id="avatar" src="../static/images/avatar.png">
		<form action="." method="POST">
			{% csrf_token %}
			<div id="errorMsg" class="fade-in one">{{ mensaje }}</div>
			{{ form.as_p }}
			<input id="loginBtn" type="submit" value="Ingresar">
			<div id="olvidoCont">¿Olvid&oacute; su contraseña?</div>
		</form>
	</div>
	<div id="nuevaCuenta">Crear nueva cuenta</div>-->
	<div class="container">
        <div class="card card-container">
            <form action="." method="POST" class="form-signin">
            	{% csrf_token %}
                <span id="reauth-email" class="reauth-email"></span>
                <div id="errorMsg" class="fade-in one">{{ mensaje }}</div>
                <input type="text" id="username" name="username" class="form-control" placeholder="Usuario" required autofocus>
                <input type="password" id="password" name="password" class="form-control" placeholder="Contraseña" required>
                <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Ingresar</button>
            </form><!-- /form -->
            <a href="{% url 'reset_password_reset1' %}" class="forgot-password">
                ¿Olvidó su contraseña?
            </a>
        </div><!-- /card-container -->
    </div><!-- /container -->
    <div id="nuevaCuenta"><a href="/"><--Regresar a menú principal</a></div>
	{% endblock %}
</body>
</html>